# Generated by Django 3.2.7 on 2021-10-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_user', '0002_auto_20211009_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_superuser',
        ),
    ]
