# Generated by Django 3.2.7 on 2021-10-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_user', '0003_rename_is_admin_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
