# Generated by Django 3.2.7 on 2021-10-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_user', '0004_auto_20211009_1456'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
