# Generated by Django 3.2.7 on 2021-10-09 20:05

from django.db import migrations
import lawyer_user.User


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_user', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', lawyer_user.User.UserManager()),
            ],
        ),
    ]
